version: '3'

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf-security-test
    ports:
      - "8888:8080"
    environment:
      - DOCKER_ENABLE_SECURITY=true
    volumes:
      - ./configs:/configs
    restart: unless-stopped
